export const CHANGE_CURRENCY_PAIR = "CHANGE_CURRENCY_PAIR";
export const CONVERT = "CONVERT";
export const UPDATE_CURRENCY_RATES_RELATIVE_TO_DOLLAR = "UPDATE_CURRENCY_RATES_RELATIVE_TO_DOLLAR";

export const SHOW_LOADING_WINDOW = "SHOW_LOADING_WINDOW";
export const HIDE_LOADING_WINDOW = "HIDE_LOADING_WINDOW";