export const CHANGE_CURRENCY_PAIR = "CHANGE_CURRENCY_PAIR";
export const CHANGE_CURRENT_PAIR_QUANTITY = "CHANGE_CURRENT_PAIR_QUANTITY";
export const UPDATE_CURRENCY_RATES_RELATIVE_TO_DOLLAR = "UPDATE_CURRENCY_RATES_RELATIVE_TO_DOLLAR";